# Java Gradle CircleCI 2.0 configuration file
# See: https://circleci.com/docs/2.0/language-java/
version: 2.1

orbs:
  android: circleci/android@2.2.0


# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build-androidlibrary:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      # specify the version you desire here
      - image: cimg/android:2023.02

    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Download depenencies
          command: ./gradlew androidDependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # build project
      - run: 
          name: build project
          command: ./gradlew clean assemble

      # run tests
      - run:
          name: run tests
          command: ./gradlew test

      - run:
          name: deploy Maven artifacts to Github Packages
          command: mvn clean deploy
  #Run test Job        
  run-test-on-emulator:      
      executor:
        name: android/android-machine
        resource-class: large
        tag: "tests-tag"
      
      steps:
        - checkout
        #Creates an AVD called avd
        - android/create-avd:
            avd-name: avd
            system-image : system-images;android-29;default;x86
            install: true

        - android/start-emulator:
            avd-name: avd
            no-window: true
            restore-gradle-cache-prefix: v1a
      # Runs "./gradlew connectedDebugAndroidTest" by default.
      # Specify the "test-command" parameter to customize the command run.
        - android/run-tests
        - android/save-gradle-cache:
            cache-prefix: v1a


    

workflows:
  build-androidibrary-and-test-workflow:
    jobs:
      - build-androidlibrary
      - run-test-on-emulator
      # - android/run-ui-tests:
      #     system-image: system-images;android-29;default;x86